# STAT 207 Group Lab Assignment 3 - [10 total points]

## Manipulating and Combining Data to Answer Questions

<hr>

## <u>Lab Grading</u>:

Should we grade your submission?  If not, write the netID of the submission to be graded.  (Note: We will only grade one assignment per group, and we'll pick the first one that says we should grade that submission.  We will assign the same grade to all team members.)

*For example*, you might respond: **grade this submission** or **my submission is under netID jdeeke**

mdm16

If you said **my submission is under netID** above, we will not read any more of your lab submission.

If you said **grade this submission** above, who worked with you on this submission?  Write both their **names** and **netIDs**.  Also, record how long each of you thinks that you could play a favorite game in one sitting.

**Note:** you may also wish to look over **Project 1** and consider making plans with any extra time, including discussing potential groups and datasets with other students in your lab section.

## <u>Purpose</u>:
You should work in groups of 2-3 on this report (not working in groups without permission will result in a point deduction). The purpose of this group lab assignment is to adjust data to be able to answer questions and provide insights from the data.
<hr>

## <u>Assignment Instructions</u>:

### Group Roles

Suggested and specified roles are provided below: 

#### Groups of 2

* **Driver**: This student will type the report.  While typing the report, you may be the one who is selecting the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  Specific ways to help may include: outlining the general steps needed to solve a question (providing the overview), locating examples within the course notes, and reviewing each line of code as it is typed.

#### Groups of 3

* **Driver**: This student will type the report.  They may also be the one to select the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  They may select the general approach to answering the question and/or a few steps to be completed along the way. 
* **Communicator**: This student will review the report (as it is typed) to ensure that it is clear and concise.  This student may also locate relevant examples within the course notes that may help complete the assignment.

<hr>

We encourage each student to record their own answers for the lab, so that you have access to your answers.  We suggest this to encourage you to engage with the content and to create a resource for future assignments.

### Imports

In [1]:
#Run this
import pandas as pd                    # imports pandas and calls the imported version 'pd'
import matplotlib.pyplot as plt        # imports the package and calls it 'plt'
import seaborn as sns                  # imports the seaborn package with the imported name 'sns'
sns.set()

## Steam Data

Steam is the world's most popular PC Gaming hub. They have a massive catalog of games, with everything from AAA blockbusters to small indie titles.  You are a team of data scientists working for Steam, and you are responsible for completing analysis for a report that will go to the executives of Valve (the parent company for Steam). 

Unfortunately, the data were collected with a less than optimal structure.  The dataset is comprised of transactions within the Steam platform for a random sample of 500 steam users along with their complete purchase and game play behaviors.  It has the following columns:
* user_id,
* game_name,
* activity:
    - purchase: indicating that the user has *purchased* the corresponding game
    - play: indicating that the user has *played* the corresponding game (for at least some amount of time.) 
* hours_played_if_play:
    - if the row corresponds to a 'play' activity, this number represents the number of hours the user has played the game
    - if the row corresponds to a 'purchase' activity, this number is always a 1 (and means nothing... it's a placeholder).

Note that for each user-game combo, there will either be one row (if the game has only been purchased but not played) or two rows (if the game has been both purchased and played).

**The executives have tasked you with identifying the games that are played the most to help them with an upcoming advertising campaign.**

### 1. [0.5 point] Reading in the Data

Read in the steam_sample.csv file into a dataframe, being sure to read in missing data correctly.  Drop the observations with missing values.  *Hint:* you can return to Lab 2 Questions 1 & 2, where you performed these steps.

Also, separate the data into a purchase and a play data frame, for the purchase rows and the play rows, respectively (Question 4 of Lab 2).

In [11]:
df = pd.read_csv('steam_sample.csv', na_values='unknown')
df.head()

     user_id  game_name  activity  hours_played_if_play
0  308653033   Unturned  purchase                   1.0
1  308653033   Unturned      play                   0.6
2  308653033  theHunter  purchase                   1.0
3  144004384     Dota 2  purchase                   1.0
4  144004384     Dota 2      play                  22.0

In [12]:
df_purchase = df[df['activity'] == 'purchase']
df_play = df[df['activity'] == 'play']

### 2. [3 points] Games as the Unit of Observation

In Lab 2, we calculated the proportion of purchased games that were played.  In Questions 2 and 3, we want to identify games that are must-play games.  These would be the game(s) that the executives could highlight during the advertising campaign.  In order to define our must-play games, we'll explore the proportion of purchases that were played based on the game, with specific tasks below that help with this calculation.

In Question 2, we will adjust the unit of observation in our data to the game and then calculate variables (measures) for each game.  In Question 3, we will then combine our datasets to answer our question of interest.

After Question 1, our original unit of observation in the data is the user-game combo, where each row corresponds to a specific user-game combination with variables about purchasing or playing that game.

**a)** First, create a data frame with two variables: the game and the number of users that purchased each game.  Make sure that you clean your data frame so that it is easy to use.

In [ ]:
df.dropna(inplace=True)

In [15]:
df.isna().sum()

user_id                 0
game_name               0
activity                0
hours_played_if_play    0
dtype: int64

In [34]:
df1 = df_purchase.groupby('game_name').agg('user_id').count().reset_index().sort_values('user_id', ascending=False)
df1

                                              game_name  user_id
379                                              Dota 2      197
1201                                    Team Fortress 2       95
264                     Counter-Strike Global Offensive       67
1356                                           Unturned       54
266                               Counter-Strike Source       50
...                                                 ...      ...
701                                      Let the Cat In        1
703                                  Lichdom Battlemage        1
706                     Lilly and Sasha Guardian Angels        1
707                                      Little Inferno        1
0     1... 2... 3... KICK IT! (Drop That Beat Like a...        1

[1445 rows x 2 columns]

**b)** From the data frame in **part a**, determine the number of distinct games that were purchased by the users in our data.  Each game should be counted only once, regardless of how many users have purchased the game.  You will use this number later to check that all games are in your final data.

In [31]:
games_purchased = df1.shape[0]
games_purchased

1445

**c)** Then, create a data frame that calculates the number of users that played each game.  Again, make sure that you clean your data frame.

In [32]:
df2 = df_play.groupby('game_name').agg('user_id').count().reset_index().sort_values('user_id', ascending=False)
df2

                               game_name  user_id
254                               Dota 2      197
774                      Team Fortress 2       95
170      Counter-Strike Global Offensive       63
869                             Unturned       43
172                Counter-Strike Source       37
..                                   ...      ...
428                    Iron Grip Warlord        1
429                            Jamestown        1
430  Joe Dever's Lone Wolf HD Remastered        1
431               Jurassic Park The Game        1
460                   Lichdom Battlemage        1

[920 rows x 2 columns]

**d)** From the data frame in **part c**, determine the number of distinct games that were played by the users in our data.  Again, each game should be counted only once, regardless of how many users have purchased the game.  

Does this number match the games calculated in **part b**?  Do these numbers seem plausible?

In [35]:
games_played = df2.shape[0]
games_played

920

### 3. [3.5 points] What is the Purchase to Play Conversion for Steam Games?

Now that we have our two variables of interest calculated for each game (our new unit of observation), we can combine the measures and answer how many games are must-play games.

**a)** Merge your data frames from **parts a and c**, being sure that you retain any game that appears in at least one of the two data frames.  *Hint*: Look up the pandas `merge` function, looking at the `how` parameter (input) in particular.  Try a few options for the `how` parameter.  Check the dimensions of the resulting data frame to see if your data contains the desired number of games (observations) that you identified in Question 2.

**b)** Add a purchase-to-play conversion variable to the data by calculating the number of users who have played that game divided by the number of users who have purchased the game.  You should have one calculated value for each game.

**c)** What proportion of games in the data have a purchase-to-play conversion rate of 1 (that is every user who purchases the game also plays the game)?  These are the must-play games that you would send to the executives for the advertising campaign.

### 4. [3 points] How Much Are Games Played?

In Questions 2 and 3, we used the purchase-to-play conversion to define must-play games.  Now, we will consider a different approach at defining which games are played the most: how long each game is played.  In other words, we might be looking to represent how captivating a game is after it is opened by recording how long a typical user plays the game.

**a)** Create a variable for the median time users spent playing a game, using the game as the unit of observation.  Prepare and clean it appropriately.  In other words, for each game, calculate the median time that users spent playing the game.

**b)** Summarize the values for this variable, with a visualization or numerical summaries (or both).  There are multiple appropriate approaches that you could use.

**c)** If the executives are looking for a threshold for especially captivating games (games where a typical user plays the game for an especially long period of time), what cutoff would you suggest?  You may be able to answer this question from part **b**, and you can also perform any additional analyses that you'd like.

*Note*: there is not one correct answer for this question.  This question allows you to explore your data and make a subjective decision about where you would draw the cutoff for captivating games, before sending your list of captivating games to the advertising executives.

### 5. AI Acknowledgement

Our course policy is that you should write all of your own interpretations and other narrative answers (phrases or sentences) yourself without the assistance of AI.  AI should not be used on Questions 2d and 4c of this assignment.  

You may use AI to help guide your code, although you should write all of your own code yourself (not copy-paste from another source) and you should cite your use of AI.  I would encourage you to try to generate any necessary code yourself first using course resources and using AI as a debugging tool if/when you reach an error that you can't figure out or to help you perform any coding tasks that are more advanced than we've demonstrated during class (intended only for projects).  

Did you use AI on this assignment?  Did you use other resources outside of our course-provided resources on this assignment?

If you used AI or other resources, answer the following questions to cite your usage.

- Which AI and/or resources did you use?
- What prompts did you ask it?
- How did you integrate the responses into your assignment?  Specifically, which questions or parts are associated with this usage?

Note: answering these three questions are enough for our course but may not be enough for a different course or context.

<hr>

If you have extra time during lab, you may consider organizing for Project 1 (arranging your group and picking your dataset).  You may also use this time to study for the quiz or get started on the project.  Be sure to read the Project 1 instructions carefully as you work through the project.