# STAT 207 Group Lab Assignment 8 - [10 total points]

## Confidence Interval Properties

<hr>

## <u>Lab Grading</u>:

Should we grade your submission?  If not, write the netID of the submission to be graded.  (Note: We will only grade one assignment per group, and we'll pick the first one that says we should grade that submission.  We will assign the same grade to all team members.)

*For example*, you might respond: **grade this submission** or **my submission is under netID jdeeke**

mdm16

If you said **my submission is under netID** above, we will not read any more of your lab submission.

If you said **grade this submission** above, who worked with you on this submission?  Write both their **names** and **netIDs**.  Also, discuss and record your favorite Pokemon, for those who play Pokemon.

<hr>

## <u>Purpose</u>:
You should work in groups of 2-3 on this report (not working in groups without permission will result in a point deduction). The purpose of this group lab assignment is to explore properties of confidence intervals.
<hr>

## <u>Assignment Instructions</u>:

### Group Roles

Suggested and specified roles are provided below: 

#### Groups of 2

* **Driver**: This student will type the report.  While typing the report, you may be the one who is selecting the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  Specific ways to help may include: outlining the general steps needed to solve a question (providing the overview), locating examples within the course notes, and reviewing each line of code as it is typed.

#### Groups of 3

* **Driver**: This student will type the report.  They may also be the one to select the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  They may select the general approach to answering the question and/or a few steps to be completed along the way. 
* **Communicator**: This student will review the report (as it is typed) to ensure that it is clear and concise.  This student may also locate relevant examples within the course notes that may help complete the assignment.

<hr>

## 0. [0.5 pts] Imports

In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

<hr>

## <u>Case Study</u>: Pokemon Confidence Intervals

We previously explored the Pokemon dataset in Lab 5.  Recall that this dataset contains information about all current Pokemon, including those recently released in Generation 9 (2023).  

The variables in the data include:

- **Height**: height (m)
- **Weight**: weight (kg)
- **Type1**: the primary type of the Pokemon
- **Ability1**: the primary ability of the Pokemon
- **Ability_Hidden**: the hidden ability of the Pokemon, if one is present
- **Get_Rate**: the rate at which the Pokemon can be captured (higher = easier to capture)
- **HP**: the hit point, which is how much damage a Pokemon can sustain before fainting
- **Attack**: the damage a Pokemon can inflict with a physical move
- **Defense**: the damage a Pokemon receives when hit with a physical move
- **SP_Attack**: the damage a Pokemon can inflict with a special move
- **SP_Defense**: the damage a Pokemon receives when hit with a special move
- **Speed**: speed, which determines the order in which Pokemon can move
- **Total**: the sum of each of the base statistics (HP, Attack, Defense, SP_Attack, SP_Defense, and Speed).

There are other variables in the data, which you are allowed to use if you understand their provided values.  More information about this dataset can be found at https://www.kaggle.com/datasets/takamasakato/pokemon-all-status-data.

We'll also use a second dataset, `deeke.csv`, which has information about the 104 Pokemon that my family has collected.

### 1. [1.5 pt] Population Information

**a)** Read in the population data.

In [11]:
df = pd.read_csv('Pokedex_Ver9.csv')
df

,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,Ability1,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
0,1,1_0,Bulbasaur,Bulbasaur,1,0.7,6.9,Grass,Poison,Overgrow,...,65,65,45,318,0,0,0,1,0,0
1,2,2_0,Ivysaur,Ivysaur,1,1.0,13.0,Grass,Poison,Overgrow,...,80,80,60,405,0,0,0,1,1,0
2,3,3_0,Venusaur,Venusaur,1,2.0,100.0,Grass,Poison,Overgrow,...,100,100,80,525,0,0,0,2,1,0
3,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,Thick Fat,...,122,120,80,625,0,0,0,2,1,0
4,4,4_0,Charmander,Charmander,1,0.6,8.5,Fire,NaN,Blaze,...,60,50,65,309,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,1006,1006_0,Iron Valiant,Iron Valiant,9,1.4,35.0,Fairy,Fighting,Quark Drive,...,120,60,116,590,0,3,0,0,0,0
1199,1007,1007_0,Koraidon,Koraidon,9,2.5,303.0,Fighting,Dragon,Orichalcum Pulse,...,85,100,135,670,0,3,0,0,0,0
1200,1008,1008_0,Miraidon,Miraidon,9,3.5,240.0,Electric,Dragon,Hadron Engine,...,135,115,135,670,0,0,0,3,0,0
1201,1009,1009_0,Walking Wake,Walking Wake,9,3.5,280.0,Water,Dragon,Protosynthesis,...,125,83,109,590,0,0,0,3,0,0
1202,1010,1010_0,Iron Leaves,Iron Leaves,9,1.5,125.0,Grass,Psychic,Quark Drive,...,70,108,104,590,0,3,0,0,0,0

**b)** Pick a variable and a reasonable characteristic for that variable to explore for this lab.  

For the population of all Pokemon, calculate your characteristic for your variable of interest.  This is your parameter of interest for this lab.

In [12]:
parameter = df['Speed'].mean()
parameter

np.float64(69.9609310058188)

**c)** Define your parameter of interest.  That is, report the value and what it means in a sentence.

The parameter is the true mean Speed of all Pokemon in the dataset

### 2. [4 pts] Creating a Confidence Interval

While we technically have the population of all Pokemon (and therefore can-and have-calculated our true parameter of interest), we will pretend that you only have the information available to my family about Pokemon.  To do so, you will use my family's Pokemon data to generate a confidence interval for your parameter of interest that you selected in **1b**.  By having the population, you can then "check" our confidence interval to see how well it performs. 

**a)** Provide your best estimate for the population parameter based on my family's data.

In [18]:
deeke = pd.read_csv('deeke.csv')
statistic = deeke['Speed'].mean()
statistic

np.float64(64.17307692307692)

**b)** Using my sample of size 104, simulate an estimated sampling distribution for your characteristic of interest from **1b**.

In [21]:
sim = []
for i in range(5000):
    sample = deeke['Speed'].sample(104,replace=True)
    sim.append(sample.mean())
sim = pd.Series(sim)
sim

0       65.423077
1       62.259615
2       65.855769
3       62.105769
4       66.096154
          ...
4995    63.500000
4996    60.961538
4997    64.403846
4998    69.759615
4999    63.009615
Length: 5000, dtype: float64

**c)** From your simulated sampling distribution, calculate an 85% confidence interval for your parameter of interest.

In [23]:
lower = sim.quantile(0.075)
upper = sim.quantile(0.925)

(lower, upper)

(np.float64(60.38461538461539), np.float64(68.01995192307693))

**d)** For the first time in this assignment, we will recognize that we do have access to our population data and therefore can access the parameter of interest.

Is your confidence interval "good"?  That is, does your confidence interval capture the value for the true parameter of interest?

**For full credit, find the answer to this question using code & logical statements in one line of code**.

In [25]:
lower <= parameter <= upper

np.False_

### 3. [3 pt] Creating Repeated Confidence Intervals

In Question 2, we generated a confidence interval based on my family's data.  My family has captured 104 Pokemon, but what about other Pokemon players who have also captured 104 Pokemon?  What would their intervals look like?

We'd like to learn more about the behavior of confidence intervals in general, so we'd like to observe what happens when we have different samples of Pokemon throughout this question.

For this question, do the following:

- Generate 1000 random samples (each of size 104 without replacement) from the population of all Pokemon
- Calculate the 85% confidence interval for each sample
- Record whether the confidence interval contains the population parameter

Be sure to record whether the confidence interval contains the population parameter.  You may also record other information, although this is not required.

*Hint 1: Using two `for` loops, where one occurs inside the other will likely help you with this process.*

*Hint 2: As you approach this process, you may want to look back on the code you used in <b>Q2b - 2d</b>*.

*Hint 3: If you find that you are stuck, try first to complete the steps described above for a single random sample.  Then, extend the process 1000 times using a `for` loop.*

In [28]:
interval_results = []

for i in range(1000):
    sample_i = df["Speed"].sample(n=104, replace=False)
    
    sim_i = []
    for j in range(1000):
        boot_i = sample_i.sample(n=104, replace=True)
        sim_i.append(boot_i.mean())
    
    sim_i = pd.Series(sim_i)
    lower_i = sim_i.quantile(0.075)
    upper_i = sim_i.quantile(0.925)
    contains_param = lower_i <= parameter <= upper_i
    
    interval_results.append([lower_i, upper_i, contains_param])

In [29]:
intervals_df = pd.DataFrame(interval_results, columns=["lower", "upper", "contains_param"])
intervals_df.head()

       lower      upper  contains_param
0  60.219712  69.069471           False
1  64.710817  74.029567            True
2  63.970433  72.318750            True
3  60.691587  68.779567           False
4  66.142788  74.048798            True

### 4. [1 pt] Calculating the Proportion of Confidence Intervals Containing Our Parameter

**a)** From the output of the 1000 random samples, calculate the proportion of confidence intervals that contain our parameter.

In [30]:
intervals_df["contains_param"].mean()

np.float64(0.871)

**b)** Does the proportion that you calculated in part **a** match with the anticipated behavior of confidence intervals?  Briefly explain.

The proportion should be around 85%, so yes this is anticipated as the proportion we have calculated is very close to the 85% we anticipated.

### 5. AI Acknowledgement

Our course policy is that you should write all of your own interpretations and other narrative answers (phrases or sentences) yourself without the assistance of AI.  AI should not be used on Questions 1c and 4d of this assignment.  

You may use AI to help guide your code, although you should write all of your own code yourself (not copy-paste from another source) and you should cite your use of AI.  I would encourage you to try to generate any necessary code yourself first using course resources and using AI as a debugging tool if/when you reach an error that you can't figure out or to help you perform any coding tasks that are more advanced than we've demonstrated during class (intended only for projects).  

Did you use AI on this assignment?  Did you use other resources outside of our course-provided resources on this assignment?

None

If you used AI or other resources, answer the following questions to cite your usage.

- Which AI and/or resources did you use?
- What prompts did you ask it?
- How did you integrate the responses into your assignment?  Specifically, which questions or parts are associated with this usage?

Note: answering these three questions are enough for our course but may not be enough for a different course or context.

N/A