# STAT 207 Homework 4 [25 points]

## Sampling Distributions

Due: Monday, February 23, end of day (11:59 pm CT)

Late submissions accepted until Tuesday, February 24 at noon

<hr>

## Python Component

Run the following code chunk to import the packages needed for this assignment:

- pandas
- matplotlib.pyplot
- seaborn

The first package assists in analyzing a dataset.  The second two packages provide support for visualizations.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Case Study: Bob Ross

The Joy of Painting was a 30-minute instructional painting show where host Bob Ross would instruct viewers on how to create their own paintings.  In the 403 episodes that were produced, a painting was completed during the episode.  Many common objects were showcased throughout the paintings, including various landscapes, animals, and other natural features.

Our population of interest will be all paintings Bob Ross painted on his television program.

Below, we'll combine two datasets with relevant information about Bob Ross paintings, including the following variables of interest:
- **season**: the season of the painting
- **episode**: the episode of the painting
- **num_colors**: the number of paint colors used for the painting
- **OVAL_FRAME**: whether the painting used an oval frame (1 = included, 0 = excluded)
- **SNOWY_MOUNTAIN**: whether a snowy mountain was included in the painting (1= included, 0 = excluded)

The below code cell reads in the data, cleans it, and prepares it for analysis.

In [3]:
paint_colors = pd.read_csv("https://raw.githubusercontent.com/jwilber/Bob_Ross_Paintings/master/data/bob_ross_paintings.csv")
objects = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-06/bob-ross.csv")
objects['season'] = objects['EPISODE'].str[1:3]
objects['season'] = objects['season'].astype(int)
objects['episode'] = objects['EPISODE'].str[4:]
objects['episode'] = objects['episode'].astype(int)
df = paint_colors.merge(objects, on = ['episode', 'season'])

## 1. Summarize the Paintings [0.5 points]

**a)** Generate numerical summaries for the number of colors variable (`num_colors`) for this data.

In [8]:
df['num_colors'].agg(['mean', 'std', 'min', 'max', 'median','count'])

mean       10.650124
std         2.388648
min         1.000000
max        15.000000
median     11.000000
count     403.000000
Name: num_colors, dtype: float64

**b)** Extra Gradescope Calculations

I'd suggest turning to Q1 on Gradescope here.

I don't anticipate a need to perform any more calculations or analyses for this problem.  This space is available for any optional calculations or analyses that you'd like.

(403, 98)

## 2. Locating One Painting [0.5 point]

**a)** Locate the Winter Oval painting from Season 9, Episode 5 and show the data for this painting.  

Tip: We can use the **`&`** ("and") operator to indicate that we want **both** conditions on either side of the operator to be met.  We can use the **`|`** ("or") operator to indicate that we want **at least one** of the conditions to be met.  We can also chain these operators together if we need to represent more complex operations.

In [28]:
x = df[(df['season'] == 9) & (df['episode'] == 5)]

**b)** Extra Gradescope Calculations

I'd suggest turning to Q2 on Gradescope here.

You'll likely need to further explore the data for Gradescope Q2.  You can use this section for any exploration that you'd like, although there are no points associated with this part.

In [22]:
x['num_colors']

108    7
Name: num_colors, dtype: int64

In [29]:
len(df[df['num_colors'] <= 7])/len(df)

0.11910669975186104

In [32]:
len(df[(df['num_colors'] <= 7 ) & (df['OVAL_FRAME'] == 1)])/len(df[df['OVAL_FRAME']==1])

0.13157894736842105

In [34]:
len(df[(df['num_colors'] <= 7 ) & (df['SNOWY_MOUNTAIN'] == 1)])/len(df[df['SNOWY_MOUNTAIN']==1])

0.14678899082568808

In [35]:
y = df[df['SNOWY_MOUNTAIN'] == 1]['num_colors'].agg(['mean', 'std', 'min', 'max', 'median','count'])
z = df['num_colors'].agg(['mean', 'std', 'min', 'max', 'median','count'])
y,z

(mean       10.642202
 std         2.760579
 min         3.000000
 max        15.000000
 median     12.000000
 count     109.000000
 Name: num_colors, dtype: float64,
 mean       10.650124
 std         2.388648
 min         1.000000
 max        15.000000
 median     11.000000
 count     403.000000
 Name: num_colors, dtype: float64)

## 3. Oval-Framed Paintings [2.5 points]

**a)** Let's now look at the paintings that are oval-framed.  Filter the data to only those paintings with that include an oval frame (`OVAL_FRAME`).

In [ ]:
df_oval = df[df['OVAL_FRAME'] == 1]

38

**b)** Generate a sampling distribution from all Bob Ross paintings for our variable of interest (mean number of colors used) and a sample size (the number of oval-framed paintings) to match our statistic of interest.  You can use 5000 repeated random samples for this question, and you should sample with replacement.  Show your sampling distribution.

In [64]:
means = []
for i in range(5000):
    df_sample = df.sample(len(df_oval), replace = True)
    means.append(df_sample['num_colors'].mean())
means = pd.DataFrame(means, columns=['mean_num_colors'])
means

      mean_num_colors
0           10.394737
1           11.078947
2           10.236842
3           10.500000
4           10.500000
...               ...
4995        11.052632
4996        10.473684
4997        10.868421
4998        10.342105
4999        11.394737

[5000 rows x 1 columns]

**c)** Extra Gradescope Calculations

I'd suggest turning to Q3 on Gradescope here.

You'll likely need to further explore the data for Gradescope Q3.  You can use this section for any exploration that you'd like, although there are no points associated with this part.

In [38]:
len(df_oval)

38

In [48]:
x = df_oval['num_colors'].agg(['mean'])
x

mean    10.394737
Name: num_colors, dtype: float64

In [66]:
len(means[means['mean_num_colors'] <= x['mean']]) / len(means)

0.2644

In [68]:
means['mean_num_colors'].agg(['mean', 'std'])

mean    10.645216
std      0.388197
Name: mean_num_colors, dtype: float64

## 4. Comparing Paintings [0 points]

Extra Gradescope Calculations

I'd suggest continuing with Q4 on Gradescope here.  I don't anticipate a need to perform any more calculations or analyses for this problem.  This space is available for any optional calculations or analyses that you'd like.  All points for Question 4 will come from Gradescope.

## 5. Sampling Distributions for Paintings with Oval Frames [2 points]

You will need to generate two sampling distributions for this question.  For these sampling distributions, be sure to sample with replacement.

**a)** First, generate a sampling distribution with 1000 repetitions.  As your statistic of interest, use the proportion of paintings that have an oval frame, and use 31 as the sample size.

In [100]:
samp_dist = []
for i in range(1000):
    df_sample = df.sample(31, replace = True)
    samp_dist.append((df_sample['OVAL_FRAME'].mean()))
df_dist = pd.DataFrame(samp_dist, columns=['mean_oval_frame'])
df_dist

     mean_oval_frame
0           0.129032
1           0.096774
2           0.032258
3           0.064516
4           0.000000
..               ...
995         0.096774
996         0.064516
997         0.161290
998         0.096774
999         0.129032

[1000 rows x 1 columns]

**b)** Now, generate a second sampling distribution with 5000 repetitions.  As your statistic of interest, use the proportion of paintings that have an oval frame, and use 13 as the sample size.

In [99]:
samp = []
for i in range(5000):
    df_sample = df.sample(13, replace = True)
    samp.append((df_sample['OVAL_FRAME'].mean()))
dist = pd.DataFrame(samp, columns=['mean_oval_frame'])
dist

      mean_oval_frame
0            0.076923
1            0.153846
2            0.000000
3            0.153846
4            0.076923
...               ...
4995         0.076923
4996         0.000000
4997         0.230769
4998         0.076923
4999         0.076923

[5000 rows x 1 columns]

**c)** Extra Gradescope Calculations

I'd suggest turning to Q5 on Gradescope here.

You'll likely need to further explore the data for Gradescope Q5.  You can use this section for any exploration that you'd like, although there are no points associated with this part.

In [92]:
df.value_counts('OVAL_FRAME', normalize=True)

OVAL_FRAME
0    0.905707
1    0.094293
Name: proportion, dtype: float64

In [101]:
last_season = df[df['season'] == 31]
p = last_season.value_counts('OVAL_FRAME', normalize=True)
p[1]

np.float64(0.07692307692307693)

In [103]:
len(dist[dist['mean_oval_frame'] <= p[1]])/len(dist)

0.659

## 6. AI Acknowledgement

Our course policy is that you should write all of your own interpretations and other narrative answers (phrases or sentences) yourself without the assistance of AI.  You may use AI to help guide your code, although you should write all of your own code yourself (not copy-paste from another source) and you should cite your use of AI.  I would encourage you to try to generate any necessary code yourself first using course resources and using AI as a debugging tool if/when you reach an error that you can't figure out or to help you perform any coding tasks that are more advanced than we've demonstrated during class (intended only for projects).  

Did you use AI on this assignment?  Did you use other resources outside of our course-provided resources on this assignment?

I did not use ai

If you used AI or other resources, answer the following questions to cite your usage.

- Which AI and/or resources did you use (including links, if appropriate)?
- What prompts did you ask it?
- How did you integrate the responses into your assignment?  Specifically, which questions or parts are associated with this usage?

Note: answering these three questions are enough for our course but may not be enough for a different course or context.

N/A

Remember to keep all your cells and hit the save icon above periodically to checkpoint (save) your results on your local computer. Once you are satisified with your results restart the kernel and run all (Kernel -> Restart & Run All). **Make sure nothing has changed**. Checkpoint and exit (File -> Save and Checkpoint + File -> Close and Halt). Follow the instructions on the Homework 4 Canvas Assignment to submit your notebook to GitHub.  Be sure to also complete the Gradescope component of this assignment.